### ISSUE TITLE
"Backend Error" not handled

### ISSUE THREAD

**Issue by espindola** [gauteh/gmailieer#10]
I noticed I had a "new" tag in every message.  A leftover from my old notmuch config. I removed it from all messages, and ran "gmi sync". It started checking every message flags against the remote, and eventually failed with the attached log. Maybe it should retry?

[log.txt](https://github.com/gauteh/gmailieer/files/900862/log.txt)

**Comment by gauteh** [comment]
Yes, according to `drive` API docs (which were the only I could find
something about 500 about) one should do an exponential backoff and
re-try. Currently, we don't do this in a batch way for push.

The 'new' tag should be ignored, but it will trigger an update since the
local db revision is incremented.

Rafael Ávila de Espíndola writes on april 5, 2017 23:37:

**Comment by gauteh** [comment]
Should be fixed in latest master.
