### ISSUE TITLE
use a batch method when pushing

### ISSUE THREAD

**Issue by yeled** [gauteh/gmailieer#20]
just like pulling. This is useful if you decide to run `notmuch tag --batch` and it touches 80k files.

**Comment by gauteh** [comment]
Charlie Allom writes on mai 10, 2017 4:45:
> just like pulling. This is useful if you decide to run `notmuch tag --batch` and it touches 80k files.
> 

Yes, we'd have to re-structure the push a little bit since we need to
check which changes should be made (if any). So, we'd have to:

1. get all changed messages from remote that changed, this is easy to do
   in batch since `get_messages` already is batchified. we don't need
   the full content, just the minimal/meta-version.
2. store this list of meta-data so that `update` can check vs it.
   `update` needs to:
   a) decide which labels should be added and removed
   b) return a batch operation that will be added to the queue and
      submitted later.
   c) check if any new labels have to be created on the gmail side,
      these should also be submitted to the queue and done before the
      message changes are executed (in batch mode).

It shouldn't be too hard since the remote request that are constructed
already in `update` can just be added to a batch query rather than being
`.execute()`'ed directly as they are now.

**Comment by gauteh** [comment]
Please test #21.

**Comment by gauteh** [comment]
Fixed in #21.
