### ISSUE TITLE
customize ignoring tags

### ISSUE THREAD

**Issue by nv1t** [gauteh/gmailieer#32]
I'm using "snoozing" mails quite often. Atm i'm removing the inbox tag and adding two new tags: snooze, snoozeuntil-<date>. If <date> matches the current date the email will get readded to inbox :)

gmi syncs both tags towards gmail and clutters the taglist.

Ignoring tags is a thing already. It would be nice to customize it :)

**Comment by julian-klode** [comment]
And snooze is actually a gmail tag too (well, you can query it in the web UI, it returns items snoozed in the Inbox client), that probably confuses the web UI :)

I'd like custom ignore, because I'd like to unignore SPAM and TRASH.

**Comment by nv1t** [comment]
Haven't seen snooze. Web-UI snoozed mails don't have any tags assoziated, or i'm missing stuff :-/

**Comment by julian-klode** [comment]
Yeah, you don't see it, but you can query is:snoozed in gmail and it returns emails snoozed in Inbox - that's not documented anywhere, though.

**Comment by gauteh** [comment]
Julian Andres Klode writes on juni 13, 2017 21:25:
> And snooze is actually a gmail tag too (well, you can query it in the web UI, it returns items snoozed in the Inbox client), that probably confuses the web UI :)
> 
> I'd like custom ignore, because I'd like to unignore SPAM and TRASH.

These are not included by default by the Gmail API, I don't know if that
can be switched on - or if we need to fetch them separately.

Adding arbitrary non-gmail-special tags to be ignored, like 'new' and
'attachment' in ignore_labels should be trivial. This should probably be
exposed using the `gmi set` interface, so that they are done on a
per-account basis. It would make sense to have these in the global
.notmuch-config, but I think it would get messy.

**Comment by gauteh** [comment]
nv1t writes on juni 13, 2017 20:56:
> I'm using "snoozing" mails quite often. Atm i'm removing the inbox tag and adding two new tags: snooze, snoozeuntil-<date>. If <date> matches the current date the email will get readded to inbox :)

I'm using a similar approach using queue and queue.date---, how do you
catch e-mails that you missed one day (say if you're computer is off for
more than 48 hours)? Regexp tags?

**Comment by nv1t** [comment]
i'm sorting the queue.date and use the "unsnooze" method on each tag below a certain date. It is much faster, than regexp manipulation.
One method would be using simple unix time. I'm using a yyyymmdd type date, which makes it easier for input, coz i haven't worked on setting up custom commands/hooks. I don't need the extra time component and by date is enough.

i have a third tag which is snoozedBy. I can enter relative times and a timed python script translates these into absolute values :)

It seems the snoozed label is not included as well, which is a bummer.

**Comment by gauteh** [comment]
Ok, so to sum up:

- Ignoring arbitrary tags is easy.
- Un-ignoring `spam` and `trash` is not.

**Comment by nv1t** [comment]
Adding: Ignoring arbitrary tags based on regexp, or search string.

**Comment by Eising** [comment]
I would like to request this feature too.

Since I use multiple gmail accounts, it would be nice to be able to tag them so I can distinguish them locally, but I don't want that tag to be synced to gmail.

**Comment by amitramon** [comment]
This seems like a good time to mention that I've started to work on a new feature for gmi, a custom translation of labels that can be configured by the user. It is in final stage and mostly need some more testing, so I hope to create a pull request for this feature in a few days.

I'm mentioning it here because it is related to the issue of the 'disallowed' labels discussed here. Also, I agree that @Eising 's use case is a good one, it would be useful to allow users to use tags locally without having to push them to their Gmail's accounts.

Since the implementation of this 'custom ignored labels' seems to me quiet similar to what I'm doing in the 'custom label translation' feature, I'll see if I can add it to what I'm doing or, perhaps, add it later in its own pull request.

**Comment by gauteh** [comment]
Cool, looking forward to see how it works.

**Comment by amitramon** [comment]
@gauteh - I have just created a pull request :-)

**Comment by gauteh** [comment]
Try #81 for a simple custom ignore

**Comment by gauteh** [comment]
Fixed in #81. No regexp support yet.
