### ISSUE TITLE
Multiple gmail accounts?

### ISSUE THREAD

**Issue by paralin** [gauteh/gmailieer#56]
Is there a good way of setting up multiple accounts in a single repository?

**Comment by gauteh** [comment]
Christian Stewart writes on desember 6, 2017 22:02:
> Is there a good way of setting up multiple accounts in a single repository?

No, do not do that. Create a sub-directory and create your repositories 
below that (one dir for each). Notmuch doesn't care about directory 
layout as long as it is below the root mail directory.

**Comment by kontheocharis** [comment]
It seems that once this is done, notmuch gets confused with all the tags (since it indexes both accounts) and it ends up being that sent emails from account A are also sent to the inbox folder of account A, and a lot of messages in the form of "xx is not in this repository, ignoring" pop up.
Any idea how this could be resolved?

**Comment by gauteh** [comment]
Notmuch identifies emails with the mail ID. If you have the same email in
two accounts this will result in tags propagating between the accounts. You
do not have any other emails in the Gmail folders for the accounts? They
should have one exclusive folder each.

tor. 24. okt. 2019, 18:33 skrev Constantine Theocharis <
notifications@github.com>:

**Comment by kontheocharis** [comment]
I don't, that's the weird thing. My directory structure is as follows:
~/.local/share/mail/ is the notmuch root directory.
~/.local/share/mail/account.gmail1/ is the first gmail account and
~/.local/share/mail/account.gmail2/ is the second. They are both indexed by
notmuch. But when for example I send an email from gmail1 to some other
address (not gmail2), the email also appears in the inbox of gmail1. I
don't know why this is. I presume that spending some time to debug this
would get me to the root cause. However, I've decided to move to an
IMAP-based solution due to this and other problems with tag-based email.
Nevertheless, good work on this project, it is truly cool! Thanks for the
reply.

>

**Comment by gauteh** [comment]
Ok :)
