### ISSUE TITLE
Implement gmi send

### ISSUE THREAD

**Issue by gauteh** [gauteh/gmailieer#71]
Implement gmi send which sends messages using [Users.messages.send](https://developers.google.com/gmail/api/v1/reference/users/messages/send), adds the messages instantly to the local repository and applies specified tags. Should  be a drop-in for sendmail and support common functionality (e.g. the subset implemented by msmtp).

If drafts are supported this should use [Drafts.send](https://developers.google.com/gmail/api/v1/reference/users/drafts/send), but as far as I can see this will add a significant layer of complexity and we could skip that for now.

**Comment by julian-klode** [comment]
Note that sending a message via the gmail API essentially _requires_ specifying the thread id for replies. So you need some magic to figure that out based on the message you are sending. Because otherwise, gmail does not try to find a matching thread itself, but will just not group them into any conversation...

**Comment by gauteh** [comment]
That should be possible, we now which message-id it is a reply to and we have the mid-gid map already. We then need to loop through all mids and gids untill we get a thread-id match from GMail.

**Comment by gauteh** [comment]
I think this is not going to be a priority after all. Closing.

**Comment by gauteh** [comment]
See #131
