### ISSUE TITLE
Syncing the currently ignored CATEGORY_* labels [wishlist]

### ISSUE THREAD

**Issue by aplaice** [gauteh/gmailieer#87]
Would it be possible to have an option to not ignore the special CATEGORY_* labels, or ideally a chosen subset of them? Currently their ignoring seems to be [hardcoded](https://github.com/gauteh/gmailieer/blob/master/lieer/remote.py#L57).

AFAICT the reason they're ignored is that they're rather verbose and often (though not always — sometimes they're actually useful, hence this issue) not very helpful, so it makes sense to ignore them by default, rather than because of technical issues. According to the [API guide](https://developers.google.com/gmail/api/guides/labels), they can be manually applied. Testing (by the barbaric method of just removing the relevant lines) shows that they can indeed be both pulled and pushed (adding or removing the label) without any problems. I think that no special precautions would need to be taken when syncing them.

However, I'm not sure how best to provide the option of unignoring them, in the gmailieer interface, without changing the very reasonable default (of them being ignored).

BTW thanks for an extraordinarily useful package!

(Also, btw am I missing something or are the [`special_labels`](https://github.com/gauteh/gmailieer/blob/master/lieer/remote.py#L37) not currently used anywhere?)

**Comment by gauteh** [comment]
aplaice writes on July 25, 2018 22:31:
> Would it be possible to have an option to not ignore the special CATEGORY_* labels, or ideally a chosen subset of them? Currently their ignoring seems to be [hardcoded](https://github.com/gauteh/gmailieer/blob/master/lieer/remote.py#L57).
> 
> AFAICT the reason they're ignored is that they're rather verbose and often (though not always — sometimes they're actually useful, hence this issue) not very helpful, so it makes sense to ignore them by default, rather than because of technical issues. According to the [API guide](https://developers.google.com/gmail/api/guides/labels), they can be manually applied. Testing (by the barbaric method of just removing the relevant lines) shows that they can indeed be both pulled and pushed (adding or removing the label) without any problems. I think that no special precautions would need to be taken when syncing them.
> 
> However, I'm not sure how best to provide the option of unignoring them, in the gmailieer interface, without changing the very reasonable default (of them being ignored).
> 
> BTW thanks for an extraordinarily useful package!
> 
> (Also, btw am I missing something or are the [`special_labels`](https://github.com/gauteh/gmailieer/blob/master/lieer/remote.py#L37) not currently used anywhere?)

Thanks :)

Yes, you are right - `special_labels` are not used anymore it seems. Maybe 
I just put it in there to document the API.. maybe git grep can shed 
some light.

The `ignore_labels` could be treated in the same way as `ignore_tags`. The 
Local() class is always set up when the Remote() is set up 
(remote.py:100). So `ignore_labels` could safely be loaded from there. I 
suggest that we just use the default values as they are now, and then 
you can reset them manually to whatever afterwards. I no longer remember 
why I put them in there, may very well be that I just thought them to be 
annoying :)

`ignore_tags` ignores tags to labels (local to remote), while 
`ignore_labels` ignores labels to tags (remote to local). This has to be 
clear from `gmi set -h` and the README as it is not particularly 
intuitive, but I still think it is useful to have these two options 
separated (maybe you have two machines syncing to the same gmail account 
and you need some way to communicate a tag/label uniquely from one 
machine).

Note that changing `ignored_labels` wont affect already synced e-mails 
when doing incremental syncs, but you could do `gmi pull -f` to do a 
full re-fetch of the metadata.

The ability to translate labels (#62) would be pretty useful here since 
`CATEGORY_PERSONAL` should just be `personal` in most cases, but this is 
a bit complicated to get right since changing this setting results in 
severe inconsistencies between local and remote.

**Comment by gauteh** [comment]
Gaute Hope writes on July 26, 2018 9:32:
> The ability to translate labels (#62) would be pretty useful here since 
> `CATEGORY_PERSONAL` should just be `personal` in most cases, but this is 
> a bit complicated to get right since changing this setting results in 
> severe inconsistencies between local and remote.

Could probably put these in to translate_labels (local.py:15)?

**Comment by gauteh** [comment]
Gaute Hope writes on July 26, 2018 9:38:
> Gaute Hope writes on July 26, 2018 9:32:
>> The ability to translate labels (#62) would be pretty useful here since 
>> `CATEGORY_PERSONAL` should just be `personal` in most cases, but this is 
>> a bit complicated to get right since changing this setting results in 
>> severe inconsistencies between local and remote.
> 
> Could probably put these in to translate_labels (local.py:15)?
> 

Please try out #89. You can un-ignore the labels by doing:

```
$ gmi set --ignore-tags-remote ""
```

This will not affect existing messages untill they are re-synced. 
Messages being pushed up might also loose these labels if you change 
this setting after having previously synced the messages.

**Comment by gauteh** [comment]
Gaute Hope writes on August 8, 2018 13:34:
> Gaute Hope writes on July 26, 2018 9:38:
>> Gaute Hope writes on July 26, 2018 9:32:
>>> The ability to translate labels (#62) would be pretty useful here since 
>>> `CATEGORY_PERSONAL` should just be `personal` in most cases, but this is 
>>> a bit complicated to get right since changing this setting results in 
>>> severe inconsistencies between local and remote.
>> 
>> Could probably put these in to translate_labels (local.py:15)?
>> 
> 
> Please try out #89. You can un-ignore the labels by doing:
> 
> ```
> $ gmi set --ignore-tags-remote ""
> ```
> 
> This will not affect existing messages untill they are re-synced. 
> Messages being pushed up might also loose these labels if you change 
> this setting after having previously synced the messages.
> 
> 

By the way, please check if the new README also makes sense to you. I 
plan on distributing it as a man page in using ronn. Looks pretty good 
out-of-the-box.

**Comment by aplaice** [comment]
This is extraordinarily, abominably late but thank you very much for having added the option to synchronise the special CATEGORY_ tags! (It works great! :))

(I had suddenly, unexpectedly become very busy and and I didn't have time to even try out the changes, at the time.)

> By the way, please check if the new README also makes sense to you.

I'm not sure if feedback on the docs is still welcome or needed, but the current README seems clear.  The new website is lovely.

> I plan on distributing it as a man page in using ronn.

Again, I have no idea whether this is current, but passing `index.md` through `ronn` gives relatively nicely formatted output (other than `ronn` not dealing well with first-level headings).

Sorry for not having replied within any reasonable timeframe...

**Comment by gauteh** [comment]
Thanks for the feedback anyway 🙂

tir. 27. aug. 2019, 16:43 skrev aplaice <notifications@github.com>:
