### ISSUE TITLE
pushing wrong maildir to Gmail

### ISSUE THREAD

**Issue by mturquette** [gauteh/gmailieer#91]
I woke up to a nasty surprise this morning: my work Gmail had thousands of new messages uploaded to it that don't belong there. I don't know if this is user error on my part or if there is a bug in how gmailieer chooses which messages to upload. Here is my configuration:

`~/.mail/work` is the gmailieer working directory for my main account. This has been working fine for a while. I have a cron job that pulls, does some tagging, and then pushes via `gmi`.

I have just added `~/.mail/archive_foo` and `~/.mail/archive_bar` that are both maildirs of dead accounts. They come from offlineimap days, before gmailieer, and I do not sync or otherwise change anything about these maildir. I do want them indexed by notmuch. They are just for historical searches.

When I initially indexed each archive I tagged all of the mails: `notmuch tag +archived-foo path:/foo/`, etc.

This morning my Gmail web interface shows a new Label, `archived-foo` with 28k emails in it :-(

Any ideas on why this happened? Is it expected behavior? For reference my cronjob, simplified for readability:

```
#!/usr/bin/env fish

set PATH ~/.config/alot/hooks $PATH

cd ~/.mail/work/

gmi pull

# fetch patwork patch status and convert into notmuch tags
fetch-pw-states-update-notmuch-tags.fish

gmi push

notmuch tag -new -- tag:new
```

So the surprising thing to me is that this script resulted in messages from outside of `~/.mail/work` getting uploaded to the gmail account associated with `work`. Is this expected behavior?

More generally, does Gmailieer's design play nice with multiple Google accounts indexed into a single notmuch database? I have to assume that a common pattern amongst Gmaillieer users is to have a work gmail and a personal gmail account, indexed together.

**Comment by gauteh** [comment]
Gmailieer cannot push new messages, only tags. As you noticed notmuch 
does not distinguish between messages with the same message id. These 
are stored as the same message, but with several different sources 
associated to it. It is therefore not possible for gmailieer to 
distinguish which tags belong to which message source file. The source 
file is used by gmailieer to identify which repository it belongs in.

`exclude_tags` in .notmuch-config is used by MUAs (alot, emacs, astroid) 
to specify a list of tags which if a message has, will not be displayed 
in searches (unless the tag is explicitly included). Gmailieer is not a 
MUA and does not use this setting.

You can however specify a per-repository ignore-tags or ignore-labels 
usign `gmi set`. This is documented in the README, check it out because 
there are some caveats about changing this after the initial sync.

Run `gmi set` in the repository to see the current (presumably default) 
settings. You probably want to add the archive tags to --ignore-tags. 
However, as mentioned, if you have messages with the same message-id on 
both accounts they will get identical tags.

**Comment by mturquette** [comment]
I've just seen this option and started reading the docs right before you responded.

On the face of it, I wonder if you would reconsider your stance on exclude_tags being MUA-only? I do not consider the following to be an MUA: `notmuch search to:linux-kernel@vger.kernel.org`, but I do expect it to filter out messages that are also tagged with an excluded tag (and it does).

I think this boils down to the principle of least surprise: the CLI tools honor the exluded tags, and it was pretty confusing for me as a user to see that gmailieer did not demonstrate the same behavior.

Furthermore, it's sort of a scalability problem if every gmi repo requires me to copy/paste these `--ignore-tags-local`. The best design would be to honor the excluded_tags globally and then allow users to set `--ignore-tags-local` for some fine-grained control per repo. Thoughts?

**Comment by gauteh** [comment]
Michael Turquette writes on September 27, 2018 22:03:
> I've just seen this option and started reading the docs right before you responded.
>
> On the face of it, I wonder if you would reconsider your stance on exclude_tags being MUA-only? I do not consider the following to be an MUA: `notmuch search to:linux-kernel@vger.kernel.org`, but I do expect it to filter out messages that are also tagged with an excluded tag (and it does).
>
> I think this boils down to the principle of least surprise: the CLI tools honor the exluded tags, and it was pretty confusing for me as a user to see that gmailieer did not demonstrate the same behavior.
>
> Furthermore, it's sort of a scalability problem if every gmi repo requires me to copy/paste these `--ignore-tags-local`. The best design would be to honor the excluded_tags globally and then allow users to set `--ignore-tags-local` for some fine-grained control per repo. Thoughts?
>

A typical `excluded_tag` is `spam`. If this is added to the ignored-tags
list you will not be able to mark gmail messages as spam. The same with
trash. But you do typically want to exclude these messages from searches
and lists. I think this illustrates the difference between the more 
clienty (notmuch search cli) and more backendy (gmailieer) parts of the 
setup.

I am fairly convinced about not changing it :) For most users you might
have two or three accounts max and changing the option on all of them is
not a very big inconvenience. I do see your point though since you could
end up with discrepancies if you forget to add it to one.

The best way to fix your problem is probably to either remove the tag on 
GMail side, then add to ignore-tags. Or add tag to ignore-tags and then 
gmi push -f (but this will change a lot of messages!! so take 
precautions and see the relevant bits in the README).

**Comment by mturquette** [comment]
Ok, thanks for the help. I'll close this issue as PEBKAC, though an additional Caveat maybe should be added to the README? Something like:

* Any tags listed as`excluded_tags` in `.notmuch-config` will still be synchronized by Gmailieer. Use `--ignore-tags-local` or `--ignore-tags-remote` as appropriate to prevent synchronizing tags between the local notmuch repository and GMail.
