### ISSUE TITLE
multiple email accounts in one notmuch database and file is not in this repository message

### ISSUE THREAD

**Issue by kvaneesh** [gauteh/gmailieer#97]
I do use single notmuch database which index emails from multiple accounts. These accounts end up having emails from different mailing list. That means i do have emails with same message-id duplicated in different filesystem directories. when running gmi sync I get the below messages always 

'/dir1/Inbox/cur/1532493124.4677_62.skywalker,U=514:2,ST' is not in this repository, ignoring.

dir1 where is I sync other email accounts and not gmail 
Following that, I always find that we are receiving metadata of about 47000 all the time. 

Anything I can do to avoid that 4k7 metadata update all the time.

-aneesh

**Comment by gauteh** [comment]
The messages with the same id are indistinguishable to notmuch, and thus to
gmailieer. And the syncing will not stabilize until the tags are the same
on all accounts. You can ignore tags per account to avoid some tags to
travel across accounts. The full update is likely caused by a incomplete
syncs. Perhaps you are syncing the accounts in parallell? Either way, by
syncing each account fully until no more changes are seen. Then the next,
and so on, will eventually make all duplicate messages have the same tags
and the sync state up to date. The ignore message will still occur, for
unsynced messages, since the message has files in several accounts, but it
does not count as an unfinished sync to gmailieer.

Gaute

fre. 28. des. 2018 kl. 03:54 skrev Aneesh Kumar K.V <
notifications@github.com>:
